[package]
name = "rust-tokio-async-directory-list"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1.8", features = ["fs" ]}
anyhow = "1.0.44"
serde_json = "1.0"